# Generated by Django 4.2.7 on 2023-11-25 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FinancasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=10000)),
                ('valor_Divida', models.FloatField(default=0)),
                ('renegociado', models.BooleanField(default=False)),
                ('qt_parcelas', models.IntegerField(default=0)),
                ('valor_total_parcelado', models.FloatField(default=0)),
                ('data_renegociacao', models.DateField(default=django.utils.timezone.now)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('parcelas_pagas', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Dividas',
        ),
    ]
