# Generated by Django 4.2.7 on 2023-11-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinancasApp', '0003_compras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financa',
            new_name='Financas',
        ),
    ]
