# Generated by Django 4.2.7 on 2023-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancasApp', '0005_remove_financas_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='renegociado',
            field=models.BooleanField(verbose_name='Não'),
        ),
    ]
