# Generated by Django 4.2.7 on 2023-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancasApp', '0006_alter_financas_renegociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='renegociado',
            field=models.BooleanField(default=False),
        ),
    ]
