# Generated by Django 4.2.7 on 2023-11-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancasApp', '0007_alter_financas_renegociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='juros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compras',
            name='parcelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compras',
            name='qt_parcelas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compras',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
